from sqlalchemy.sql import text

# Delete queries
truncate_ActsLoan = text("truncate table dbo.ActsLoan")
truncate_ActsLoanPart = text("truncate table dbo.ActsLoanPart")
truncate_alembic_version = text("truncate table dbo.alembic_version")
truncate_AmortisationScheme = text("truncate table dbo.AmortisationScheme")
truncate_ArrearsLoan = text("truncate table dbo.ArrearsLoan")
truncate_ArrearsLoanPart = text("truncate table dbo.ArrearsLoanPart")
truncate_BondLedger = text("truncate table dbo.BondLedger")
truncate_BondPrice = text("truncate table dbo.BondPrice")
truncate_BondTrade = text("truncate table dbo.BondTrade")
truncate_BondYield = text("truncate table dbo.BondYield")
truncate_CustomerPrice = text("truncate table dbo.CustomerPrice")
truncate_FullPrepayment = text("truncate table dbo.FullPrepayment")
truncate_GeneralLedger = text("truncate table dbo.GeneralLedger")
truncate_InitialInterestAllocation = text("truncate table dbo.InitialInterestAllocation")
truncate_Isin = text("truncate table dbo.Isin")
truncate_JournalEntries = text("truncate table dbo.JournalEntries")
truncate_Loan = text("truncate table dbo.Loan")
truncate_LoanBondAllocation = text("truncate table dbo.LoanBondAllocation")
truncate_LoanPartBondline = text("truncate table dbo.LoanPartBondline")
truncate_LoanType = text("truncate table dbo.LoanType")
truncate_PartialPrepayment = text("truncate table dbo.PartialPrepayment")
truncate_PFS_ArrearsSettings = text("truncate table dbo.PFS_ArrearsSettings")
truncate_PFS_BankSettings = text("truncate table dbo.PFS_BankSettings")
truncate_PFS_Cet1Percentage = text("truncate table dbo.PFS_Cet1Percentage")
truncate_PFS_EconomicScenarios = text("truncate table dbo.PFS_EconomicScenarios")
truncate_PFS_GainPrepaymentSettings = text("truncate table dbo.PFS_GainPrepaymentSettings")
truncate_PFS_LtvSettings = text("truncate table dbo.PFS_LtvSettings")
truncate_PFS_OcRequirements = text("truncate table dbo.PFS_OcRequirements")
truncate_PFS_PipelinePortfolioSettings = text("truncate table dbo.PFS_PipelinePortfolioSettings")
truncate_PFS_PortfolioSettings = text("truncate table dbo.PFS_PortfolioSettings")
truncate_PyYieldIn = text("truncate table dbo.PyYieldIn")
truncate_PyYieldOut = text("truncate table dbo.PyYieldOut")
truncate_RiskMeasure = text("truncate table dbo.RiskMeasure")

# Select queries from views
get_viewBondTypesInScope = text("select * from dbo.BondTypesInScope")
get_viewYieldInput = text("select * from dbo.YieldInput")
